package quickchat;

import javax.swing.JOptionPane;

/**
 *
 * @author mudau
 */
public class LoginPanel extends javax.swing.JFrame {

    private Login login;
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(Login login) 
    {
        this.login = login;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(187, 107, 247));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(null);

        Right.setBackground(new java.awt.Color(117, 47, 187));
        Right.setPreferredSize(new java.awt.Dimension(400, 200));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(logo)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(logo)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jPanel1.add(Right);
        Right.setBounds(0, 0, 270, 500);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("LOGIN");
        jPanel1.add(titleLabel);
        titleLabel.setBounds(270, 40, 530, 30);

        usernameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        usernameLabel.setText("Enter your Username:");
        jPanel1.add(usernameLabel);
        usernameLabel.setBounds(320, 210, 150, 25);

        usernameField.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(usernameField);
        usernameField.setBounds(480, 210, 250, 25);

        passwordLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        passwordLabel.setText("Enter your Password:");
        jPanel1.add(passwordLabel);
        passwordLabel.setBounds(320, 260, 150, 25);

        loginButton.setText("Confirm Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton);
        loginButton.setBounds(580, 340, 150, 30);

        passwordField.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(passwordField);
        passwordField.setBounds(480, 260, 250, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        String username, password;

        username = usernameField.getText();
        password =  new String(passwordField.getPassword());
  

        boolean accessGranted =
        login.loginUser(username, password);
        
        String loginFeedback = 
                login.returnLoginStatus();

        if (accessGranted)
        {
            JOptionPane.showMessageDialog(this, loginFeedback, "Access Granted", JOptionPane.INFORMATION_MESSAGE);
            MessagePanel messagePanel = new MessagePanel();
            messagePanel.startMessagingInteraction();
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, loginFeedback, "Access Denied", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Right;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
