package quickchat;

import javax.swing.JOptionPane;

/**
 *
 * @author mudau
 */
public class RegistrationPanel extends javax.swing.JFrame {

    private Registration registration;
    private Login login;
    /**
     * Creates new form RegistrationPanel
     */
    public RegistrationPanel(Registration registration, Login login) 
    {
        this.registration = registration;
        this.login = login;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        phonenumberLabel = new javax.swing.JLabel();
        cellphoneField = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        firstnameLabel = new javax.swing.JLabel();
        firstnameField = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();
        lastnameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(187, 107, 247));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(null);

        Right.setBackground(new java.awt.Color(117, 47, 187));
        Right.setPreferredSize(new java.awt.Dimension(400, 200));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(logo)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(logo)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jPanel1.add(Right);
        Right.setBounds(0, 0, 270, 500);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText(" REGISTRATION");
        jPanel1.add(titleLabel);
        titleLabel.setBounds(270, 40, 530, 30);

        usernameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        usernameLabel.setText("Create your Username:");
        jPanel1.add(usernameLabel);
        usernameLabel.setBounds(320, 210, 150, 25);

        usernameField.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(usernameField);
        usernameField.setBounds(480, 210, 250, 25);

        passwordLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        passwordLabel.setText("Create your Password:");
        jPanel1.add(passwordLabel);
        passwordLabel.setBounds(320, 260, 150, 25);

        phonenumberLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        phonenumberLabel.setText("Enter your Number: ");
        jPanel1.add(phonenumberLabel);
        phonenumberLabel.setBounds(320, 320, 150, 25);

        cellphoneField.setPreferredSize(new java.awt.Dimension(250, 25));
        cellphoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellphoneFieldActionPerformed(evt);
            }
        });
        jPanel1.add(cellphoneField);
        cellphoneField.setBounds(480, 320, 250, 25);

        registerButton.setText("Submit Registration");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton);
        registerButton.setBounds(580, 400, 150, 30);

        firstnameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        firstnameLabel.setText("Enter your First Name:");
        jPanel1.add(firstnameLabel);
        firstnameLabel.setBounds(320, 110, 150, 25);

        firstnameField.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(firstnameField);
        firstnameField.setBounds(480, 110, 250, 25);

        lastnameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lastnameLabel.setText("Enter your Last Name:");
        jPanel1.add(lastnameLabel);
        lastnameLabel.setBounds(320, 160, 150, 25);

        lastnameField.setPreferredSize(new java.awt.Dimension(250, 25));
        lastnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(lastnameField);
        lastnameField.setBounds(480, 160, 250, 25);

        passwordField.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(passwordField);
        passwordField.setBounds(480, 260, 250, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cellphoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellphoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellphoneFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed

        
        String username, password, cellphone, firstname, lastname;
        
        username = usernameField.getText();
        password =  new String(passwordField.getPassword());
        cellphone = cellphoneField.getText();
        firstname = firstnameField.getText();
        lastname = lastnameField.getText();
        
        String results =
        registration.registerUser(username, password, cellphone, firstname, lastname);
        
        if (results.contains("Your Registration was successful, you can login now"))
        {
            JOptionPane.showMessageDialog(this, results, "Registration Success", JOptionPane.INFORMATION_MESSAGE);
            LoginPanel loginPanel = new LoginPanel(login);
            loginPanel.setVisible(true);
            loginPanel.setLocationRelativeTo(null);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, results, "Registration Error", JOptionPane.ERROR_MESSAGE); 
        }
        
        
    }//GEN-LAST:event_registerButtonActionPerformed

    private void lastnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Right;
    private javax.swing.JTextField cellphoneField;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel phonenumberLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
